### ISSUE TITLE
raise_if_error with NI_RFSG

### ISSUE THREAD

**Issue by markusmat97** [ni/grpc-device#851]
I was trying to run a python example of NI_RFSG https://github.com/ni/grpc-device/blob/main/examples/nirfsg/getting-started-single-tone-generation.py.The script is modified and tried to run which outputs an error as below:

Traceback (most recent call last):
  File "J:\Projekte_111\01_xxxxx\20xxxxxxxxx_\10_software\grpc setup\1.xxxx\python integration\draft-getting-started-single-tone-generation - Copy.py", line 109, in <module>
    raise_if_error(client.Initiate(nirfsg_types.InitiateRequest(vi=vi)))
  File "J:\Projekte_111\01_xxxxx\20xxxxxxxxx\10_software\grpc setup\1.xxxx\python integration\draft-getting-started-single-tone-generation - Copy.py", line 39, in raise_if_error
    raise Exception(f"Error: {response.error_string}")
AttributeError: error_string

How to solve this issue?

[AB#2301084](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2301084)

**Comment by shastriUF** [comment]
@markusmat97 it looks like you are using an old example because `raise_if_error` was removed from the example last August (in PR #712).  That change was in response to changing how the grpc-device server reports errors (in PR #692).  So we think you have a "version mismatch" between the example and the python language bindings, and possibly the server binary as well. Can you try resolving this to use the latest? Getting this resolved will allow you to see the actual error (or warning?) being returned from Initiate.

**Comment by shastriUF** [comment]
Closing this issue, please re-open or file a new issue if updating the examples does not work
